### PR TITLE
WC Customer Dashboard #22

### LINKED ISSUE #22: Remove WC Customer Dashboard Fields
**Customer**
|#426 - https://projects.vta.org/projects/copy-center/work_packages/426 
|#427 - https://projects.vta.org/projects/copy-center/work_packages/427
|#428 - https://projects.vta.org/projects/copy-center/work_packages/428
|#432 - https://projects.vta.org/projects/copy-center/work_packages/432

**Admin** 
|#429 - https://projects.vta.org/projects/copy-center/work_packages/429
|#430 - https://projects.vta.org/projects/copy-center/work_packages/430
|#431 - https://projects.vta.org/projects/copy-center/work_packages/431

**Bugs**
|#434 - https://projects.vta.org/projects/copy-center/work_packages/434

Remove unused fields that are not applicable to the Copy Center Online Form.

**Requirements:**

### Customer Dashboards
- [x] Hide the **Downloads** tab from the **My Account** page.
- [x] Hide the **Address** tab from the **My Account** page.
- [x] Remove the **shipping & address** link in the **Dashboard** sub-page of the **My Account** page.
- [x] Remove **Billing Address** from the customers **Order Detail** page inside **My Account**.
- [x] Remove all unneeded pricing details from **Dashboard**

### Admin Dashboards
- [ ] ~Remove **Billing Address** & **Shipping Address** & **Downloads** from **Edit Order** page.~
- [ ] ~Remove User Billing & Address fields in the **Edit User** page.~ 
_Note: Copy Center Team is okay with these fields appearing. We may want to keep **Billing Address** since this is how WooCommerce saves customer phone number_

### Bugs & Other Requests (Meeting 5/4/2020)
- [x] ~Automatically render fields associated with Levels 1 & Levels 2~ Resolved via GF interface. Conditional Fields must be sequential...
- [x] ~Email on password reset.~ _Inactive Post SMTP plugin_
- [x] New Order Status "Proof Ready" (including email templates)
- [x] New User confirmation page.
- [x] Business Card Page buttons should be roughly the same size. Cancel should be on the left hand-size and continue on the right.
- [x] Customizer Page is currently broken (Top admin bar, click **Customize**)

_**Dashboard Styling:**_
- There may Be additional CSS styling to format WooCommerce sub-pages inside **My Account**.

### PR DESCRIPTION
**Pull request by jpham93**
**Customer**
|#426 - https://projects.vta.org/projects/copy-center/work_packages/426 
|#427 - https://projects.vta.org/projects/copy-center/work_packages/427
|#428 - https://projects.vta.org/projects/copy-center/work_packages/428
|#432 - https://projects.vta.org/projects/copy-center/work_packages/432

**Admin** 
|#429 - https://projects.vta.org/projects/copy-center/work_packages/429
|#430 - https://projects.vta.org/projects/copy-center/work_packages/430
|#431 - https://projects.vta.org/projects/copy-center/work_packages/431

**Bugs**
|#434 - https://projects.vta.org/projects/copy-center/work_packages/434

This PR removes unused customer-facing fields. In the **My Account** page, we remove anything related to billing and shipping fields. All order items also remove **Totals and Subtotals**.

**Testing:**
- Go the **My Account** page and see if there are any links/tabs that refer to Shipping and Billing address.
- Make a test order and check if **Total** and **Subtotal** appear in the **Cart** page, **Checkout** page,  and **Order Confirmation** page.
- In the WooCommerce admin panel, change the Test Order's order status to **Proof Ready** and see if it triggers an email notification.
- On the home page while logged into your WordPress admin account, click Customize in the black admin menu to see if the Customizer loads.

**Requirements:**

### Customer Dashboards
- [x] Hide the **Downloads** tab from the **My Account** page.
- [x] Hide the **Address** tab from the **My Account** page.
- [x] Remove the **shipping & address** link in the **Dashboard** sub-page of the **My Account** page.
- [x] Remove **Billing Address** from the customers **Order Detail** page inside **My Account**.
- [x] Remove all unneeded pricing details from **Dashboard**

### Admin Dashboards
- [ ] ~Remove **Billing Address** & **Shipping Address** & **Downloads** from **Edit Order** page.~
- [ ] ~Remove User Billing & Address fields in the **Edit User** page.~ 
_Note: Copy Center Team is okay with these fields appearing. We may want to keep **Billing Address** since this is how WooCommerce saves customer phone number_

### Bugs & Other Requests (Meeting 5/4/2020)
- [x] ~Automatically render fields associated with Levels 1 & Levels 2~ Resolved via GF interface. Conditional Fields must be sequential...
- [x] ~Email on password reset.~ _Inactive Post SMTP plugin_
- [x] New Order Status "Proof Ready" (including email templates)
- [x] New User confirmation page.
- [x] Business Card Page buttons should be roughly the same size. Cancel should be on the left hand-size and continue on the right.
- [x] Customizer Page is currently broken (Top admin bar, click **Customize**)

_**Dashboard Styling:**_
- There may Be additional CSS styling to format WooCommerce sub-pages inside **My Account**.

**Considerations:**
We may want to re-implement some of these fields in the future. Pricing fields (total & subtotal) may be used in cost tracking, so we would have to revert some of these templates overrides.

### CODE REVIEW

File: wp-content/themes/twentytwenty-child/functions.php [hunk 1]
```diff
@@ -242,6 +242,18 @@ function custom_override_checkout_fields( $fields )
     return $fields;
 }
 
+/**
+ * REMOVE Downloads & Address tab from "My Account"
```
Comment (bijanmmarkes) [inline wp-content/themes/twentytwenty-child/functions.php:246]: Glad we're able to do this as it could've been confusing to employees. :+1:

File: wp-content/themes/twentytwenty-child/functions.php [hunk 2]
```diff
@@ -48,7 +48,7 @@ function register_menus()
  * Start user session for each individual user
  * REQUIRED for attaching meta data to business card product
  */
-add_action( "wp_loaded", "theme_start_session", 1 );
+add_action( "init", "theme_start_session", 1 );
```
Comment (bijanmmarkes) [inline wp-content/themes/twentytwenty-child/functions.php:51]: :+1:

**Review by bijanmmarkes — APPROVED** [review]
Good job, making great progress.

We did a thorough review in today's meeting, nice to see it in the code.

:+1: :100:
